const defaultKeywords = [
  // ===== SAAS DEMOS & PRODUCT VIDEOS (pilar #1) =====
  { phrase: 'product demo video', category: 'direct', priority: 1 },
  { phrase: 'saas demo video', category: 'direct', priority: 1 },
  { phrase: 'software demo video', category: 'direct', priority: 1 },
  { phrase: 'demo video for landing page', category: 'direct', priority: 1 },
  { phrase: 'how to make product demo', category: 'direct', priority: 1 },
  { phrase: 'record saas demo', category: 'direct', priority: 1 },
  { phrase: 'how to record product demo', category: 'direct', priority: 1 },
  { phrase: 'how to record demo video', category: 'direct', priority: 1 },
  { phrase: 'tool for recording product demo', category: 'direct', priority: 1 },
  { phrase: 'product walkthrough video', category: 'direct', priority: 1 },
  { phrase: 'feature demo video', category: 'direct', priority: 1 },
  { phrase: 'app walkthrough video', category: 'direct', priority: 1 },
  { phrase: 'product tour video', category: 'direct', priority: 1 },
  { phrase: 'saas product video', category: 'direct', priority: 1 },
  { phrase: 'app demo video', category: 'direct', priority: 1 },
  { phrase: 'product showcase video', category: 'direct', priority: 1 },
  { phrase: 'video for landing page', category: 'direct', priority: 1 },
  { phrase: 'hero video landing page', category: 'direct', priority: 1 },
  { phrase: 'landing page video', category: 'direct', priority: 1 },
  { phrase: 'saas explainer video', category: 'direct', priority: 1 },
  { phrase: 'saas marketing video', category: 'direct', priority: 1 },
  { phrase: 'product marketing video', category: 'direct', priority: 1 },
  { phrase: 'startup demo video', category: 'direct', priority: 1 },
  { phrase: 'customer onboarding video', category: 'direct', priority: 2 },
  { phrase: 'product onboarding video', category: 'direct', priority: 2 },
  { phrase: 'feature announcement video', category: 'direct', priority: 2 },

  // ===== CREAR VÍDEO PARA PROMOCIONAR PRODUCTO (pilar #2) =====
  { phrase: 'how to make a promo video', category: 'question', priority: 1 },
  { phrase: 'how to make a video for my app', category: 'question', priority: 1 },
  { phrase: 'how to make a video for my saas', category: 'question', priority: 1 },
  { phrase: 'how to make a video for my website', category: 'question', priority: 1 },
  { phrase: 'how to create a promo video', category: 'question', priority: 1 },
  { phrase: 'how to create product video', category: 'question', priority: 1 },
  { phrase: 'tool to make promo video', category: 'direct', priority: 1 },
  { phrase: 'tool to create product video', category: 'direct', priority: 1 },
  { phrase: 'need video for my product', category: 'direct', priority: 1 },
  { phrase: 'need video for my app', category: 'direct', priority: 1 },
  { phrase: 'need video for my saas', category: 'direct', priority: 1 },
  { phrase: 'make video for my startup', category: 'direct', priority: 1 },
  { phrase: 'app promo video', category: 'direct', priority: 1 },
  { phrase: 'saas promo video', category: 'direct', priority: 1 },
  { phrase: 'screen recording for ad', category: 'direct', priority: 1 },
  { phrase: 'record my app for ad', category: 'direct', priority: 1 },
  { phrase: 'short promo video', category: 'direct', priority: 2 },
  { phrase: 'app store preview video', category: 'direct', priority: 2 },
  { phrase: 'video content for my startup', category: 'direct', priority: 1 },
  { phrase: 'video content for my saas', category: 'direct', priority: 1 },

  // ===== CONTENIDO VERTICAL PARA SAAS/WEB (pilar #3) =====
  { phrase: 'vertical video for saas', category: 'direct', priority: 1 },
  { phrase: 'vertical screen recording', category: 'direct', priority: 1 },
  { phrase: 'reels for my app', category: 'direct', priority: 1 },
  { phrase: 'reels for saas', category: 'direct', priority: 1 },
  { phrase: 'tiktok for saas', category: 'direct', priority: 1 },
  { phrase: 'short form content saas', category: 'direct', priority: 1 },
  { phrase: 'screen recording for reels', category: 'direct', priority: 1 },
  { phrase: 'screen recording for shorts', category: 'direct', priority: 1 },
  { phrase: 'screen recording for tiktok', category: 'direct', priority: 1 },
  { phrase: 'screen recording for twitter', category: 'direct', priority: 2 },
  { phrase: 'screen recording social media', category: 'direct', priority: 2 },
  { phrase: 'repurpose demo video', category: 'direct', priority: 1 },
  { phrase: 'repurpose product video', category: 'direct', priority: 1 },
  { phrase: 'saas content creation', category: 'direct', priority: 1 },
  { phrase: 'startup content creation', category: 'direct', priority: 1 },
  { phrase: 'product content for social media', category: 'direct', priority: 1 },
  { phrase: 'how do you show your product', category: 'question', priority: 1 },
  { phrase: 'how to show my app', category: 'question', priority: 1 },
  { phrase: 'how to promote my saas', category: 'question', priority: 1 },

  // ===== BUILDING IN PUBLIC / FOUNDERS =====
  { phrase: 'building in public video', category: 'direct', priority: 1 },
  { phrase: 'showcase my project', category: 'direct', priority: 1 },
  { phrase: 'product update video', category: 'direct', priority: 1 },
  { phrase: 'changelog video', category: 'direct', priority: 1 },
  { phrase: 'share what i built', category: 'direct', priority: 2 },

  // ===== DOLOR DE EDICIÓN =====
  { phrase: 'editing takes forever', category: 'pain_point', priority: 1 },
  { phrase: 'no time to edit videos', category: 'pain_point', priority: 1 },
  { phrase: 'make recording look professional', category: 'pain_point', priority: 1 },
  { phrase: 'screen recording looks unprofessional', category: 'pain_point', priority: 1 },
  { phrase: 'polish screen recording', category: 'pain_point', priority: 1 },
  { phrase: 'record screen and edit video', category: 'pain_point', priority: 1 },
  { phrase: 'record and edit demo video', category: 'pain_point', priority: 1 },
  { phrase: 'tool for recording and editing demos', category: 'pain_point', priority: 1 },
  { phrase: 'screen recording editing', category: 'pain_point', priority: 1 },
  { phrase: 'too much time editing', category: 'pain_point', priority: 1 },
  { phrase: 'quick video editing tool', category: 'pain_point', priority: 1 },

  // ===== FEATURES CLAVE (auto zoom, backgrounds, subtitles) =====
  { phrase: 'record screen with zoom', category: 'pain_point', priority: 1 },
  { phrase: 'zoom on clicks', category: 'pain_point', priority: 1 },
  { phrase: 'auto zoom recording', category: 'pain_point', priority: 1 },
  { phrase: 'auto zoom screen', category: 'pain_point', priority: 1 },
  { phrase: 'add background to screen recording', category: 'pain_point', priority: 1 },
  { phrase: 'add subtitles to screen recording', category: 'pain_point', priority: 1 },
  { phrase: 'auto captions video', category: 'pain_point', priority: 2 },
  { phrase: 'highlight clicks', category: 'pain_point', priority: 2 },

  // ===== BROWSER-BASED / NO INSTALL =====
  { phrase: 'browser screen recorder', category: 'direct', priority: 1 },
  { phrase: 'screen recorder no install', category: 'direct', priority: 1 },
  { phrase: 'screen recorder no download', category: 'direct', priority: 1 },
  { phrase: 'web based screen recorder', category: 'direct', priority: 1 },
  { phrase: 'record screen in browser', category: 'direct', priority: 1 },
  { phrase: 'online screen recorder', category: 'direct', priority: 2 },
  { phrase: 'chrome screen recorder', category: 'direct', priority: 2 },

  // ===== QUEJAS DE HERRAMIENTAS =====
  { phrase: 'loom is expensive', category: 'pain_point', priority: 1 },
  { phrase: 'loom limitations', category: 'pain_point', priority: 1 },
  { phrase: 'screen studio too expensive', category: 'pain_point', priority: 1 },
  { phrase: 'screen studio windows', category: 'pain_point', priority: 1 },
  { phrase: 'loom expensive', category: 'pain_point', priority: 1 },
  { phrase: 'loom no editing', category: 'pain_point', priority: 1 },

  // ===== PREGUNTAS DE INTENCIÓN FUERTE =====
  { phrase: 'how do you create demo videos', category: 'question', priority: 1 },
  { phrase: 'how do you record product demos', category: 'question', priority: 1 },
  { phrase: 'recommend screen recorder', category: 'question', priority: 1 },
  { phrase: 'what do you use to record', category: 'question', priority: 1 },
  { phrase: 'best tool for screen recording', category: 'question', priority: 1 },
  { phrase: 'what screen recorder do you use', category: 'question', priority: 1 },
  { phrase: 'how to record professional demo', category: 'question', priority: 1 },

  // ===== BÚSQUEDA DIRECTA (genérica, prioridad baja) =====
  { phrase: 'looking for screen recorder', category: 'direct', priority: 2 },
  { phrase: 'best screen recording software', category: 'direct', priority: 2 },
  { phrase: 'best screen recorder', category: 'direct', priority: 2 },
  { phrase: 'record demo video', category: 'direct', priority: 2 },
  { phrase: 'screen recorder', category: 'direct', priority: 3 },
  { phrase: 'screen recording app', category: 'direct', priority: 3 },
];

module.exports = defaultKeywords;
